steps:
  - label: ':package: :lambda: Lambda'
    agents:
      docker: 'true'
      queue: build
    branches: '!master !test-*'
    command: make all

  - label: ':package: :lambda: Lambda'
    agents:
      docker: 'true'
      queue: build
    artifact_paths:
      - build/lambda.zip
    branches: master test-*
    command: make all
    key: package_lambda

  - label: ':s3: Upload Lambda to S3 (hetest)'
    agents:
      queue: test1
    branches: master test-*
    command: aws s3 cp build/lambda.zip s3://hetest-s3-antivirus-lambda-code/bucket-antivirus-function-$BUILDKITE_BUILD_NUMBER.zip
    depends_on:
      - package_lambda
    plugins:
      - artifacts#v1.9.4:
          download:
            - build/lambda.zip

  - label: ':s3: Upload Lambda to S3 (heaws)'
    agents:
      queue: prod1
    branches: master
    command: aws s3 cp build/lambda.zip s3://heaws-s3-antivirus-lambda-code/bucket-antivirus-function-$BUILDKITE_BUILD_NUMBER.zip
    depends_on:
      - package_lambda
    plugins:
      - artifacts#v1.9.4:
          download:
            - build/lambda.zip
